# todo: build and test only affected
# todo: codecov after
name: on-pull-request
on: pull_request

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  MOZ_HEADLESS: 1
#  SAUCE_USERNAME_PR: valorkinpr
#  SAUCE_ACCESS_KEY_PR: e0a97bd3-4b74-4408-89bf-cce1b44a8bf1
  CYPRESS_CACHE_FOLDER: 'node_modules/.cypress'
  CYPRESS_RECORD_KEY: 4aa7a1c0-3a4f-444e-b324-6fc305a543a8

jobs:
  build_and_cache:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v2.3.4
      # start: npm ci && build
      - uses: actions/cache@v2.1.4
        id: cache-build
        with:
          path: |
            ~/.npm
            node_modules
            dist
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: npm ci
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          npm ci
      # end: npm ci && build
      - run: |
          npx ng build --runner cloud --prod --with-deps
          npx nx run ngx-bootstrap:build-sass --runner cloud
      - run: npx cypress verify

  unit_tests_with_coverage:
    runs-on: ubuntu-latest
    needs: build_and_cache
    steps:
      - uses: actions/checkout@v2.3.4

      # start: npm ci && build
      - uses: actions/cache@v2.1.4
        id: cache-build
        with:
          path: |
            ~/.npm
            node_modules
            dist
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: npm ci && npm run build --prod
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          npm ci
          npx ng build --runner cloud --prod --with-deps
          npx nx run ngx-bootstrap:build-sass --runner cloud
      # end: npm ci && build

      - run: npm test --  --runner cloud --codeCoverage
        continue-on-error: true
      - run: npx codecov ./coverage/
        continue-on-error: true

  linting:
    runs-on: ubuntu-latest
    needs: build_and_cache
    steps:
      - uses: actions/checkout@v2.3.4

      # start: npm ci && build
      - uses: actions/cache@v2.1.4
        id: cache-build
        with:
          path: |
            ~/.npm
            node_modules
            dist
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: npm ci && npm run build --prod
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          npm ci
          npx ng build --runner cloud --prod --with-deps
          npx nx run ngx-bootstrap:build-sass --runner cloud
      # end: npm ci && build

      - run: npm run lint -- --runner cloud
        continue-on-error: true

  firebase_preview:
    runs-on: ubuntu-latest
    needs: build_and_cache
    outputs:
      output_url: ${{ steps.firebase_hosting_preview.outputs.details_url }}
    steps:
      - uses: actions/checkout@v2.3.4

      # start: npm ci && build
      - uses: actions/cache@v2.1.4
        id: cache-build
        with:
          path: |
            ~/.npm
            node_modules
            dist
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: npm ci && npm run build --prod
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          npm ci
          npx ng build --runner cloud --prod --with-deps
          npx nx run ngx-bootstrap:build-sass --runner cloud
      # end: npm ci && build

      - run: npm run scully
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: firebase_hosting_preview
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NGX_BOOTSTRAP_DEMO }}'
          projectId: ngx-bootstrap-demo
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

  e2e_smoke:
    name: Cypress run
    runs-on: ubuntu-latest
    needs: [build_and_cache, firebase_preview]

    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v2.3.4

      # start: npm ci && build
      - uses: actions/cache@v2.1.4
        id: cache-build
        with:
          path: |
            ~/.npm
            node_modules
            dist
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: npm ci && npm run build --prod
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          npm ci
          npx ng build --runner cloud --prod --with-deps
          npx nx run ngx-bootstrap:build-sass --runner cloud
      # end: npm ci && build

      - run: npx cypress verify
      - name: smoke e2e
        continue-on-error: true
        run: npx nx run ci-docs-e2e:e2e --runner cloud --record --group smoke --baseUrl=${{ needs.firebase_preview.outputs.output_url }}/ngx-bootstrap/ -- --parallel

      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves

