name: Deploy to Firebase Hosting on PR
on: pull_request

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  CYPRESS_RECORD_KEY: 4aa7a1c0-3a4f-444e-b324-6fc305a543a8

jobs:
  build_and_preview:
    runs-on: ubuntu-latest

    outputs:
      output_url: ${{ steps.firebase_hosting_preview.outputs.details_url }}

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build -- --prod
      - run: npm run lint
        continue-on-error: true
      - run: npm test
        continue-on-error: true
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: firebase_hosting_preview
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NGX_BOOTSTRAP_DEMO }}'
          projectId: ngx-bootstrap-demo
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    needs: build_and_preview
    env:
      MOZ_HEADLESS: 1
      SAUCE_USERNAME_PR: valorkinpr
      SAUCE_ACCESS_KEY_PR: e0a97bd3-4b74-4408-89bf-cce1b44a8bf1
      CYPRESS_RECORD_KEY: 4aa7a1c0-3a4f-444e-b324-6fc305a543a8
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run e2e -- --baseUrl=${{ needs.build_and_preview.outputs.output_url }}/# --record --parallel --ciBuildId=${{ github.run_id }} --group=integration-${{ github.run_id }}
      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves

